/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DriverIndexRouteImport } from './routes/driver.index'
import { Route as CustomerIndexRouteImport } from './routes/customer.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as DriverRegisterRouteImport } from './routes/driver.register'
import { Route as DriverOrdersRouteImport } from './routes/driver.orders'
import { Route as DriverLoginRouteImport } from './routes/driver.login'
import { Route as CustomerWalletRouteImport } from './routes/customer.wallet'
import { Route as CustomerOrderRouteImport } from './routes/customer.order'
import { Route as CustomerLoginRouteImport } from './routes/customer.login'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as AdminReportsRouteImport } from './routes/admin.reports'
import { Route as AdminPaymentMethodsRouteImport } from './routes/admin.payment-methods'
import { Route as AdminOrdersRouteImport } from './routes/admin.orders'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as AdminFinanceRouteImport } from './routes/admin.finance'
import { Route as AdminDriversRouteImport } from './routes/admin.drivers'
import { Route as AdminCustomersRouteImport } from './routes/admin.customers'
import { Route as AdminCommissionsRouteImport } from './routes/admin.commissions'
import { Route as AdminCitiesRouteImport } from './routes/admin.cities'
import { Route as CustomerProfileCompleteRouteImport } from './routes/customer.profile.complete'
import { Route as CustomerOrdersIdRouteImport } from './routes/customer.orders.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerIndexRoute = CustomerIndexRouteImport.update({
  id: '/customer/',
  path: '/customer/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRegisterRoute = DriverRegisterRouteImport.update({
  id: '/driver/register',
  path: '/driver/register',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverOrdersRoute = DriverOrdersRouteImport.update({
  id: '/driver/orders',
  path: '/driver/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverLoginRoute = DriverLoginRouteImport.update({
  id: '/driver/login',
  path: '/driver/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerWalletRoute = CustomerWalletRouteImport.update({
  id: '/customer/wallet',
  path: '/customer/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrderRoute = CustomerOrderRouteImport.update({
  id: '/customer/order',
  path: '/customer/order',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerLoginRoute = CustomerLoginRouteImport.update({
  id: '/customer/login',
  path: '/customer/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPaymentMethodsRoute = AdminPaymentMethodsRouteImport.update({
  id: '/admin/payment-methods',
  path: '/admin/payment-methods',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersRoute = AdminOrdersRouteImport.update({
  id: '/admin/orders',
  path: '/admin/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminFinanceRoute = AdminFinanceRouteImport.update({
  id: '/admin/finance',
  path: '/admin/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDriversRoute = AdminDriversRouteImport.update({
  id: '/admin/drivers',
  path: '/admin/drivers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCustomersRoute = AdminCustomersRouteImport.update({
  id: '/admin/customers',
  path: '/admin/customers',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommissionsRoute = AdminCommissionsRouteImport.update({
  id: '/admin/commissions',
  path: '/admin/commissions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCitiesRoute = AdminCitiesRouteImport.update({
  id: '/admin/cities',
  path: '/admin/cities',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerProfileCompleteRoute = CustomerProfileCompleteRouteImport.update({
  id: '/customer/profile/complete',
  path: '/customer/profile/complete',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomerOrdersIdRoute = CustomerOrdersIdRouteImport.update({
  id: '/customer/orders/$id',
  path: '/customer/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/wallet': typeof CustomerWalletRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/orders': typeof DriverOrdersRoute
  '/driver/register': typeof DriverRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/profile/complete': typeof CustomerProfileCompleteRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/wallet': typeof CustomerWalletRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/orders': typeof DriverOrdersRoute
  '/driver/register': typeof DriverRegisterRoute
  '/admin': typeof AdminIndexRoute
  '/customer': typeof CustomerIndexRoute
  '/driver': typeof DriverIndexRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/profile/complete': typeof CustomerProfileCompleteRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/cities': typeof AdminCitiesRoute
  '/admin/commissions': typeof AdminCommissionsRoute
  '/admin/customers': typeof AdminCustomersRoute
  '/admin/drivers': typeof AdminDriversRoute
  '/admin/finance': typeof AdminFinanceRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/orders': typeof AdminOrdersRoute
  '/admin/payment-methods': typeof AdminPaymentMethodsRoute
  '/admin/reports': typeof AdminReportsRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/customer/login': typeof CustomerLoginRoute
  '/customer/order': typeof CustomerOrderRoute
  '/customer/wallet': typeof CustomerWalletRoute
  '/driver/login': typeof DriverLoginRoute
  '/driver/orders': typeof DriverOrdersRoute
  '/driver/register': typeof DriverRegisterRoute
  '/admin/': typeof AdminIndexRoute
  '/customer/': typeof CustomerIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/customer/orders/$id': typeof CustomerOrdersIdRoute
  '/customer/profile/complete': typeof CustomerProfileCompleteRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin/cities'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/reports'
    | '/auth/callback'
    | '/customer/login'
    | '/customer/order'
    | '/customer/wallet'
    | '/driver/login'
    | '/driver/orders'
    | '/driver/register'
    | '/admin/'
    | '/customer/'
    | '/driver/'
    | '/customer/orders/$id'
    | '/customer/profile/complete'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/cities'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/reports'
    | '/auth/callback'
    | '/customer/login'
    | '/customer/order'
    | '/customer/wallet'
    | '/driver/login'
    | '/driver/orders'
    | '/driver/register'
    | '/admin'
    | '/customer'
    | '/driver'
    | '/customer/orders/$id'
    | '/customer/profile/complete'
  id:
    | '__root__'
    | '/'
    | '/admin/cities'
    | '/admin/commissions'
    | '/admin/customers'
    | '/admin/drivers'
    | '/admin/finance'
    | '/admin/login'
    | '/admin/orders'
    | '/admin/payment-methods'
    | '/admin/reports'
    | '/auth/callback'
    | '/customer/login'
    | '/customer/order'
    | '/customer/wallet'
    | '/driver/login'
    | '/driver/orders'
    | '/driver/register'
    | '/admin/'
    | '/customer/'
    | '/driver/'
    | '/customer/orders/$id'
    | '/customer/profile/complete'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminCitiesRoute: typeof AdminCitiesRoute
  AdminCommissionsRoute: typeof AdminCommissionsRoute
  AdminCustomersRoute: typeof AdminCustomersRoute
  AdminDriversRoute: typeof AdminDriversRoute
  AdminFinanceRoute: typeof AdminFinanceRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminOrdersRoute: typeof AdminOrdersRoute
  AdminPaymentMethodsRoute: typeof AdminPaymentMethodsRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  CustomerLoginRoute: typeof CustomerLoginRoute
  CustomerOrderRoute: typeof CustomerOrderRoute
  CustomerWalletRoute: typeof CustomerWalletRoute
  DriverLoginRoute: typeof DriverLoginRoute
  DriverOrdersRoute: typeof DriverOrdersRoute
  DriverRegisterRoute: typeof DriverRegisterRoute
  AdminIndexRoute: typeof AdminIndexRoute
  CustomerIndexRoute: typeof CustomerIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  CustomerOrdersIdRoute: typeof CustomerOrdersIdRoute
  CustomerProfileCompleteRoute: typeof CustomerProfileCompleteRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/': {
      id: '/customer/'
      path: '/customer'
      fullPath: '/customer/'
      preLoaderRoute: typeof CustomerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/register': {
      id: '/driver/register'
      path: '/driver/register'
      fullPath: '/driver/register'
      preLoaderRoute: typeof DriverRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/orders': {
      id: '/driver/orders'
      path: '/driver/orders'
      fullPath: '/driver/orders'
      preLoaderRoute: typeof DriverOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/login': {
      id: '/driver/login'
      path: '/driver/login'
      fullPath: '/driver/login'
      preLoaderRoute: typeof DriverLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/wallet': {
      id: '/customer/wallet'
      path: '/customer/wallet'
      fullPath: '/customer/wallet'
      preLoaderRoute: typeof CustomerWalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/order': {
      id: '/customer/order'
      path: '/customer/order'
      fullPath: '/customer/order'
      preLoaderRoute: typeof CustomerOrderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/login': {
      id: '/customer/login'
      path: '/customer/login'
      fullPath: '/customer/login'
      preLoaderRoute: typeof CustomerLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/payment-methods': {
      id: '/admin/payment-methods'
      path: '/admin/payment-methods'
      fullPath: '/admin/payment-methods'
      preLoaderRoute: typeof AdminPaymentMethodsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders': {
      id: '/admin/orders'
      path: '/admin/orders'
      fullPath: '/admin/orders'
      preLoaderRoute: typeof AdminOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/finance': {
      id: '/admin/finance'
      path: '/admin/finance'
      fullPath: '/admin/finance'
      preLoaderRoute: typeof AdminFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/drivers': {
      id: '/admin/drivers'
      path: '/admin/drivers'
      fullPath: '/admin/drivers'
      preLoaderRoute: typeof AdminDriversRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/customers': {
      id: '/admin/customers'
      path: '/admin/customers'
      fullPath: '/admin/customers'
      preLoaderRoute: typeof AdminCustomersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/commissions': {
      id: '/admin/commissions'
      path: '/admin/commissions'
      fullPath: '/admin/commissions'
      preLoaderRoute: typeof AdminCommissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/cities': {
      id: '/admin/cities'
      path: '/admin/cities'
      fullPath: '/admin/cities'
      preLoaderRoute: typeof AdminCitiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/profile/complete': {
      id: '/customer/profile/complete'
      path: '/customer/profile/complete'
      fullPath: '/customer/profile/complete'
      preLoaderRoute: typeof CustomerProfileCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customer/orders/$id': {
      id: '/customer/orders/$id'
      path: '/customer/orders/$id'
      fullPath: '/customer/orders/$id'
      preLoaderRoute: typeof CustomerOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminCitiesRoute: AdminCitiesRoute,
  AdminCommissionsRoute: AdminCommissionsRoute,
  AdminCustomersRoute: AdminCustomersRoute,
  AdminDriversRoute: AdminDriversRoute,
  AdminFinanceRoute: AdminFinanceRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminOrdersRoute: AdminOrdersRoute,
  AdminPaymentMethodsRoute: AdminPaymentMethodsRoute,
  AdminReportsRoute: AdminReportsRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  CustomerLoginRoute: CustomerLoginRoute,
  CustomerOrderRoute: CustomerOrderRoute,
  CustomerWalletRoute: CustomerWalletRoute,
  DriverLoginRoute: DriverLoginRoute,
  DriverOrdersRoute: DriverOrdersRoute,
  DriverRegisterRoute: DriverRegisterRoute,
  AdminIndexRoute: AdminIndexRoute,
  CustomerIndexRoute: CustomerIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  CustomerOrdersIdRoute: CustomerOrdersIdRoute,
  CustomerProfileCompleteRoute: CustomerProfileCompleteRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
