-- ADMIN-OPS-NOTIFICATIONS-V1
-- Durable, idempotent notifications generated by trusted database state changes.

CREATE OR REPLACE FUNCTION public.emit_order_notifications()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  _driver_user uuid;
  _title text;
  _body text;
  _type public.notification_type;
  _short text := upper(left(NEW.id::text, 8));
BEGIN
  IF NEW.driver_id IS DISTINCT FROM OLD.driver_id AND NEW.driver_id IS NOT NULL THEN
    SELECT user_id INTO _driver_user FROM public.drivers WHERE id = NEW.driver_id;

    IF _driver_user IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.notifications
      WHERE user_id = _driver_user AND order_id = NEW.id
        AND title = 'طلب جديد مُسند إليك'
    ) THEN
      INSERT INTO public.notifications(user_id, order_id, type, title, body)
      VALUES (_driver_user, NEW.id, 'general', 'طلب جديد مُسند إليك',
        'تم تعيينك للطلب #' || _short || ' في ' || NEW.city || '.');
    END IF;

    IF NOT EXISTS (
      SELECT 1 FROM public.notifications
      WHERE user_id = NEW.customer_id AND order_id = NEW.id
        AND title = 'تم تعيين سائق لطلبك'
    ) THEN
      INSERT INTO public.notifications(user_id, order_id, type, title, body)
      VALUES (NEW.customer_id, NEW.id, 'general', 'تم تعيين سائق لطلبك',
        'تم إسناد الطلب #' || _short || ' إلى سائق، ويمكنك متابعة مراحله الآن.');
    END IF;
  END IF;

  IF NEW.status IS DISTINCT FROM OLD.status THEN
    CASE NEW.status
      WHEN 'approved' THEN
        _type := 'order_approved'; _title := 'تم اعتماد طلبك';
        _body := 'الطلب #' || _short || ' تم اعتماده من الإدارة.';
      WHEN 'accepted' THEN
        _type := 'order_accepted'; _title := 'قَبِل السائق طلبك';
        _body := 'قَبِل السائق الطلب #' || _short || ' وسيبدأ التحرك قريباً.';
      WHEN 'on_the_way' THEN
        _type := 'order_on_way'; _title := 'السائق في الطريق إليك';
        _body := 'سائق الطلب #' || _short || ' انطلق نحو موقعك الآن.';
      WHEN 'arrived' THEN
        _type := 'order_arrived'; _title := 'وصل السائق';
        _body := 'وصل سائق الطلب #' || _short || ' إلى موقعك.';
      WHEN 'delivering' THEN
        _type := 'order_unloading'; _title := 'بدأ تفريغ الماء';
        _body := 'بدأ السائق صب الماء للطلب #' || _short || '.';
      WHEN 'payment_collected' THEN
        _type := 'order_payment_collected'; _title := 'تم استلام المبلغ';
        _body := 'تم استلام مبلغ الطلب #' || _short || '.';
      WHEN 'completed' THEN
        _type := 'order_completed'; _title := 'اكتمل الطلب';
        _body := 'اكتمل الطلب #' || _short || ' بنجاح.';
      WHEN 'cancelled' THEN
        _type := 'order_cancelled'; _title := 'تم إلغاء الطلب';
        _body := 'تم إلغاء الطلب #' || _short || '.';
      WHEN 'rejected' THEN
        _type := 'order_rejected'; _title := 'تم رفض الطلب';
        _body := 'تم رفض الطلب #' || _short || ' من الإدارة.';
      ELSE
        _type := NULL;
    END CASE;

    IF _type IS NOT NULL AND NOT EXISTS (
      SELECT 1 FROM public.notifications
      WHERE user_id = NEW.customer_id AND order_id = NEW.id
        AND type = _type AND title = _title
    ) THEN
      INSERT INTO public.notifications(user_id, order_id, type, title, body)
      VALUES (NEW.customer_id, NEW.id, _type, _title, _body);
    END IF;
  END IF;

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_emit_order_notifications ON public.orders;
CREATE TRIGGER trg_emit_order_notifications
AFTER UPDATE OF driver_id, status ON public.orders
FOR EACH ROW EXECUTE FUNCTION public.emit_order_notifications();

CREATE OR REPLACE FUNCTION public.emit_driver_account_notification()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $$
DECLARE
  _type public.notification_type;
  _title text;
  _body text;
BEGIN
  IF NEW.user_id IS NULL OR NEW.license_status IS NOT DISTINCT FROM OLD.license_status THEN
    RETURN NEW;
  END IF;

  IF NEW.license_status = 'approved' THEN
    _type := 'driver_approved';
    _title := 'تم اعتماد حسابك';
    _body := 'تم اعتماد حسابك من الإدارة — يمكنك الآن استلام الطلبات.';
  ELSIF NEW.license_status = 'rejected' THEN
    _type := 'driver_rejected';
    _title := 'لم يتم اعتماد حسابك';
    _body := 'لم يتم اعتماد حسابك. تواصل مع إدارة المنصة لمعرفة التفاصيل.';
  ELSE
    RETURN NEW;
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM public.notifications
    WHERE user_id = NEW.user_id AND type = _type AND title = _title
      AND created_at > now() - interval '1 minute'
  ) THEN
    INSERT INTO public.notifications(user_id, order_id, type, title, body)
    VALUES (NEW.user_id, NULL, _type, _title, _body);
  END IF;
  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS trg_emit_driver_account_notification ON public.drivers;
CREATE TRIGGER trg_emit_driver_account_notification
AFTER UPDATE OF license_status ON public.drivers
FOR EACH ROW EXECUTE FUNCTION public.emit_driver_account_notification();

REVOKE ALL ON FUNCTION public.emit_order_notifications() FROM PUBLIC, anon, authenticated;
REVOKE ALL ON FUNCTION public.emit_driver_account_notification() FROM PUBLIC, anon, authenticated;